flags:
  wai-cli: { tls: false }
packages:
  - '.'
extra-deps:
  - socket-activation-0.1.0.2
  - aws-lambda-haskell-runtime-4.1.1
  - aws-lambda-haskell-runtime-wai-2.0.2
  - xml-lens-0.3.1
resolver: lts-19.28
